spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/messageInABottle
    username: root
    password: p4ssw0rd



  jpa:
    hibernate:
      ddl-auto: update